# Generated by Django 5.1.6 on 2025-03-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_user_product_user_rating_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default=1, upload_to='media/main_images', verbose_name='Главная фото'),
            preserve_default=False,
        ),
    ]
