# Generated by Django 5.1.6 on 2025-03-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
