# Generated by Django 5.1.6 on 2025-03-07 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_rating_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinganswer',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_answers', to='main.rating', verbose_name='отзыв'),
        ),
    ]
