# Generated by Django 5.1.6 on 2025-03-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default=1, upload_to='media/user_avatar', verbose_name='Аватарка'),
            preserve_default=False,
        ),
    ]
